### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by grundid** [younata/Muon#4]
Hi,

I would like to use your library but when I launch my project I get the following error message in the simulator:

dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /Users/adrian/Library/Developer/Xcode/DerivedData/MyApp-dqfjjuubszzaaybhkbfnqoysluel/Build/Products/Debug-iphonesimulator/Muon.framework/Muon
  Reason: image not found

I'm using the latest version via cocoapods:
pod 'Muon', :git => 'https://github.com/younata/Muon.git'

**Comment by younata** [comment]
Crap. So sorry about not responding to this.

**Comment by younata** [comment]
@grundid This should be fixed by https://github.com/younata/Muon/pull/2, which was just merged. Sorry for the delay.
