### ISSUE TITLE
Xcode8 + Carthage

### ISSUE THREAD

**Issue by OmarCaf** [younata/Muon#8]
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/omarcafini/Documents/Code/ksenia-user/Carthage/Checkouts/Muon/Muon.xcodeproj -scheme Muon -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

**Comment by younata** [comment]
Try the swift-3.0 branch.

**Comment by OmarCaf** [comment]
Thanks it work
